#ifndef NNPRABHUPADADB_GLOBAL_H
#define NNPRABHUPADADB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NNPRABHUPADADB_LIBRARY)
#define NNPRABHUPADADB_EXPORT Q_DECL_EXPORT
#else
#define NNPRABHUPADADB_EXPORT Q_DECL_IMPORT
#endif

#endif // NNPRABHUPADADB_GLOBAL_H
